---
- name: Install Clickhouse
  hosts: clickhouse
  handlers:
    - name: Start clickhouse service
      become: no
      ansible.builtin.service:
        name: clickhouse-server
        state: restarted
  tasks:
    - name: Create Rules
      block:
        - name: Get clickhouse distrib
          ansible.builtin.get_url:
            url: "https://packages.clickhouse.com/rpm/stable/clickhouse-client-23.9.1.1854.x86_64.rpm"
            dest: "./{{ item }}-{{ clickhouse_version }}.rpm"
            mode: "0755"
          with_items: "{{ clickhouse_packages }}"
      rescue:
        - name: Get clickhouse distrib
          ansible.builtin.get_url:
            url: "https://packages.clickhouse.com/rpm/stable/clickhouse-common-static-dbg-22.8.21.38.aarch64.rpm"
            dest: "./clickhouse-common-static-{{ clickhouse_version }}.rpm"
            mode: "0755"
    - name: Install clickhouse packages
      become: no
      ansible.builtin.yum:
        name:
          - clickhouse-common-static-{{ clickhouse_version }}.rpm
          - clickhouse-client-{{ clickhouse_version }}.rpm
          - clickhouse-server-{{ clickhouse_version }}.rpm
      notify: Start clickhouse service
# Принудительное использование handlers для сарта сервиса clickhouse-server, иначе не получится создать БД
    - name: Flush handlers
      ansible.builtin.meta: flush_handlers
# Задержка после рестарта сервера, что бы успел запустится
    - name: Delay 20 sec
      ansible.builtin.pause:
        seconds: 20
    - name: Create database
      ansible.builtin.command: "clickhouse-client -q 'create database logs;'"
      register: create_db
      failed_when: create_db.rc != 0 and create_db.rc != 82
      changed_when: create_db.rc == 0

- name: Install Vector
  hosts: vector
# handlers для старта/рестарта сервиса Vector
  handlers:
    - name: Start Vector service
      become: no
      ansible.builtin.service:
        name: vector
        state: restarted

  tasks:
# Скачивание rpm пакета vector для установки
    - name: Get Vector distrib
      ansible.builtin.get_url:
        url: "https://packages.timber.io/vector/0.21.1/vector-0.21.1-1.{{ ansible_architecture }}.rpm"
        dest: "./vector-0.21.1-1.{{ ansible_architecture }}.rpm"
        mode: "0755"
# Установка rpm пакета vector
    - name: Install Vector packages
      become: no
      ansible.builtin.yum:
        name: vector-0.21.1-1.{{ ansible_architecture }}.rpm
      notify: Start Vector service
# Создание файла конфигурации для vector. Сама конфигурация не претендует на рабочую, но пример взят с офф.документации vector
    - name: Deploy config Vector
      ansible.builtin.template:
        src: vector.j2
        dest: /etc/vector/vector.yml
        mode: "0755"
      notify: Start Vector service
